services:
    postgres:
        image: postgres:15.1
        volumes:
            - postgres_back:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
        restart: unless-stopped
        ports:
            - 5432:5432
    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'
        volumes:
            - pgadmin:/var/lib/pgadmin

volumes:
    pgadmin:
    postgres_back:
